-- Migration: Create tweet_suggestions table for content scheduling
create or replace function update_modified_column()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

create type suggestion_status as enum ('pending', 'approved', 'rejected', 'published');

create table if not exists tweet_suggestions (
    id bigint generated by default as identity primary key,
    workspace_id integer not null references workspaces(id) on delete cascade,
    content text not null,
    suggested_for_date date not null,
    status suggestion_status not null default 'pending',
    platform text not null default 'twitter',
    scheduled_at timestamp with time zone,
    published_at timestamp with time zone,
    error_message text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table tweet_suggestions enable row level security;

create policy "Users can view suggestions for their workspaces"
    on tweet_suggestions for select
    using (
        workspace_id in (
            select workspace_id from memberships
            where user_id in (
                select id from account_users where supabase_uid = auth.uid()
            )
        )
    );

create policy "Users can insert suggestions for their workspaces"
    on tweet_suggestions for insert
    with check (
        workspace_id in (
            select workspace_id from memberships
            where user_id in (
                select id from account_users where supabase_uid = auth.uid()
            )
        )
    );

create policy "Users can update suggestions for their workspaces"
    on tweet_suggestions for update
    using (
        workspace_id in (
            select workspace_id from memberships
            where user_id in (
                select id from account_users where supabase_uid = auth.uid()
            )
        )
    );

create policy "Users can delete suggestions for their workspaces"
    on tweet_suggestions for delete
    using (
        workspace_id in (
            select workspace_id from memberships
            where user_id in (
                select id from account_users where supabase_uid = auth.uid()
            )
        )
    );

create trigger set_tweet_suggestions_updated_at
    before update on tweet_suggestions
    for each row
    execute function update_modified_column();

create index if not exists idx_tweet_suggestions_workspace on tweet_suggestions(workspace_id);
create index if not exists idx_tweet_suggestions_status on tweet_suggestions(status);
create index if not exists idx_tweet_suggestions_scheduled on tweet_suggestions(scheduled_at)
    where status = 'approved' and scheduled_at is not null and published_at is null;
create index if not exists idx_tweet_suggestions_platform on tweet_suggestions(platform);
